# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.nerdbynature.me
title: nerdbynature.me
email: anders@nilssoncreative.se
author: Anders Nilsson
description: > # "Write an awesome description for your new site here.
  Maker, tinkerer and procrastinator
copyright: 'Copyright &copy; 2015 Anders Nilsson. All Rights Reserved.'
credits: 'Credits:<br/> Theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.<br />Photographs provided by <a href="http://join.deathtothestockphoto.com/">Death to the Stock Photo</a>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://facebook.com/nerbynatureme
  - title: twitter
    url: https://twitter.com/nerdbynatureme
  - title: github
    url: https://github.com/NilssonCreative
